### ISSUE TITLE
performance of cifar100

### ISSUE THREAD

**Issue by tzhxs** [ahmdtaha/simsiam#2]
Thanks for your implementation, could you provide the accuracy you got with cifar100?

**Comment by ahmdtaha** [comment]
Sure, I shall report that tonight.

**Comment by ahmdtaha** [comment]
pretrain_main.py achieves 56.xx %. Without actually running it, I expect the classifier to achieve 56+1% 
Here is the complete [pretrain sample run](https://github.com/ahmdtaha/simsiam/blob/main/sample_runs/complete_pretrain_cifar100.txt)

**Comment by tzhxs** [comment]
> pretrain_main.py achieves 56.xx %. Without actually running it, I expect the classifier to achieve 56+1%
> Here is the complete [pretrain sample run](https://github.com/ahmdtaha/simsiam/blob/main/sample_runs/complete_pretrain_cifar100.txt)

thanks for prompt reply!
