### ISSUE TITLE
What size images are supported?

### ISSUE THREAD

**Issue by turian** [ahmdtaha/simsiam#3]
I have a corpus that is not CIFAR. I am curious what other image sizes are supported?

**Comment by ahmdtaha** [comment]
This depends on your corpus and your corpus data loader. For example, the CIFAR data loader set the [image size to 32](https://github.com/ahmdtaha/simsiam/blob/d5e8211bea3d0fe44bfc8a9fd9ccfea2670738ac/data/cifar.py#L14).

For a different corpus, I recommend writing another data loader and setting the image size accordingly.
