### ISSUE TITLE
What is the purpose of the classifier_main file？

### ISSUE THREAD

**Issue by zhujilin1995** [ahmdtaha/simsiam#9]
After running `classifer_main`, I obtained the following folders.
![图片](https://github.com/ahmdtaha/simsiam/assets/30228178/dec89aa6-1f58-47c8-8566-5b1fbef5a4fc)
Among them, there is a file named `model_best.pth`. How can I use this file? Or what is the purpose of the `classifier_main` file? I haven't quite understood.

**Comment by ahmdtaha** [comment]
What is the purpose of the classifier_main file? 

> SimSiam is a self-supervised pretraining approach. After pre-training your model, you use the pre-trained model for initialization before fine-tuning on a down-stream task (e.g., a classification task).
Concretely, this repos is designed to run [pretrain_main.py](https://github.com/ahmdtaha/simsiam/blob/main/pretrain_main.py) first. After completion, use the checkpoint created by pre-training, to fine-tune a model on a down-stream task (e.g., [classifier_main.py](https://github.com/ahmdtaha/simsiam/blob/main/classifier_main.py))

Please make sure to read [SimSiam paper](https://arxiv.org/abs/2011.10566).

How can I use `model_best.pth`?
> After you train your model on a training split, you want to evaluate it on a val/test split.
Some people use the last checkpoint to evaluate their model. For instance, if a model is trained for 200 epochs, the checkpoint_200.pt is used for evaluation. Yet, this is not the only way for evaluation.
Some people use the checkpoint that achieved the best performance on the **validation split** to evaluate on a **test split**. This approach can be regarded as an [early stopping approach](https://en.wikipedia.org/wiki/Early_stopping). `model_best.pth` is the checkpoint that achieved the best performance on the **validation split**, and accordingly, you can use it evaluate on a **test split**

I hope this helps.

**Comment by zhujilin1995** [comment]
Thank you. I  have unterstood what you said. Your code is clear and straightforward. It's excellent!The folders are also well-organized. I've benefited a lot.
